version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t joncontractoracct/express-demo:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push joncontractoracct/express-demo:$CIRCLE_SHA1

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Install kubectl and argo
          command: |
            # Install kubectl and argo here...
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f rollout.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build