replicaCount: 1

image:
  repository: joncontractoracct/express-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - /
